### ISSUE TITLE
Resolve Master and Develop levels

### ISSUE THREAD

**Issue by mikael19** [spdx/license-coverage-grader#10]
@krysnuvadga @kestewart @pombredanne 

I noticed that the develop branch is behind master by 4 commits. That even prompted me to make a pull request #8 on the Master branch, which I think is not the best of practices.

I propose we take the develop branch to the same level as the master branch.

**Comment by krysnuvadga** [comment]
@thunda99 Thanks for the pull request. Best practice will be to create a new branch on your fork for every pull request not doing it directly on the master
