### ISSUE TITLE
Missing Docstring

### ISSUE THREAD

**Issue by krysnuvadga** [spdx/license-coverage-grader#14]
Most of the classes and methods are missing python document string. Adding docstring to these class and methods will be good for code maintenance and readability

**Comment by mikael19** [comment]
@krysnuvadga 
I have just gone through the codebase to increase my understanding...
I am definitely on this issue.
Expect a PR soon.
Thanks

**Comment by Satyabrat35** [comment]
@krysnuvadga 
Sir if this issue is still open? 
Then i would love to contribute 
Thanks

**Comment by krysnuvadga** [comment]
@Satyabrat35 go ahead

**Comment by Satyabrat35** [comment]
#19 Docstring added

**Comment by Satyabrat35** [comment]
#20 Docstring added 
Is it ok or i have to add something else ?
@krysnuvadga
