### ISSUE TITLE
Renaming the commands

### ISSUE THREAD

**Issue by silverhook** [spdx/license-coverage-grader#8]
Maybe I understand the `README` wrongly, but from how it reads, I fear that after installing license-coverage-grader, the command names would be too generic and therefore confusing or even clashing with some other commands on the system.

Therefore I would propose to rename them as follows:

- `grade` ↦ `spdx-coverage-grade`
- `scan` ↦ `spdx-coverage-scan`
- `check` ↦ `spdx-coverage-check`
- `analyse` ↦ `spdx-coverage-analyse`

You can probably think of a more meaningful name for at least the last three commands. I just wanted to mention what could potentially be an issue. 

Great to see this tool exist, BTW! Kudos :+1:

**Comment by mikael19** [comment]
I think that this is a good remark.
I tried to run the above commands on my unix system, and this is the result:
```
xxxx@xxxx-pc:~$ grade
No command 'grade' found, did you mean:
 Command 'gradle' from package 'gradle' (universe)
 Command 'grads' from package 'grads' (universe)
 Command 'grace' from package 'grace' (universe)
 Command 'glade' from package 'glade' (universe)
grade: command not found
xxxx@xxxx-pc:~$ analyse
analyse: command not found
xxxx@xxxx-pc:~$ scan
The program 'scan' can be found in the following packages:
 * dvb-apps
 * mailutils-mh
 * nmh
Try: sudo apt install <selected package>
xxxx@xxxx-pc:~$ check
No command 'check' found, did you mean:
 Command 'acheck' from package 'acheck' (universe)
 Command 'mcheck' from package 'mtools' (main)
 Command 'hcheck' from package 'ganeti' (universe)
 Command 'hcheck' from package 'ganeti-htools' (universe)
 Command 'vcheck' from package 'vcheck' (universe)
 Command 'chuck' from package 'chuck' (universe)
 Command 'icheck' from package 'icheck' (universe)
 Command 'fcheck' from package 'fcheck' (universe)
check: command not found
```
Judging from the above results, clashes are very likely to occur, and I agree with @silverhook .
@krysnuvadga I could work on this. I looked at the codebase, and this project is very interesting, especially because there is more room for improvement.

**Comment by krysnuvadga** [comment]
@silverhook Thanks for the pointer
@thunda99  your contributions are welcome. You can probably start by suggesting  some meaningful names for the commands

**Comment by mikael19** [comment]
@krysnuvadga 
Like @silverhook suggested, I would go for prefixes such as:
```
- spdx-
- spdx-lgrader-
```
Resulting in commands such as:
```
- spdx-scan ...
```
or
```
- spdx-lgrader-scan ...
```
These are my suggestions.

Thanks.

**Comment by krysnuvadga** [comment]
@thunda99 I think we should go with @silverhook  proposal

**Comment by mikael19** [comment]
@krysnuvadga Ok.
I shall submit a PR on this soon.

**Comment by mikael19** [comment]
@krysnuvadga @silverhook I have submitted a pull request on this. #9
